# Generated by Django 5.2.17 on 2026-09-04 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Código corto del idioma, por ejemplo ja o pt-br.",
                        max_length=10,
                        unique=True,
                        verbose_name="código",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="nombre")),
            ],
            options={
                "verbose_name": "idioma",
                "verbose_name_plural": "idiomas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="título")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("in_progress", "En progreso"),
                            ("in_review", "En revisión"),
                            ("completed", "Completado"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albums",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="propietario",
                    ),
                ),
                (
                    "source_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="albums_as_source",
                        to="albums.language",
                        verbose_name="idioma de origen",
                    ),
                ),
                (
                    "target_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="albums_as_target",
                        to="albums.language",
                        verbose_name="idioma de destino",
                    ),
                ),
            ],
            options={
                "verbose_name": "álbum",
                "verbose_name_plural": "álbumes",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "-updated_at"], name="album_owner_recent_idx"
                    ),
                    models.Index(fields=["status"], name="album_status_idx"),
                ],
            },
        ),
    ]
