# Generated by Django 5.2.17 on 2026-09-05 01:46

import django.db.models.deletion
from django.db import migrations, models

import albums.models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0002_seed_languages"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComicPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_number",
                    models.PositiveIntegerField(verbose_name="número de página"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=albums.models.page_image_path, verbose_name="imagen"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Versión reducida para la rejilla del álbum. Se genera al cargar.",
                        upload_to=albums.models.page_thumbnail_path,
                        verbose_name="miniatura",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente de procesamiento"),
                            ("processing", "Procesando"),
                            ("processed", "Procesada"),
                            ("needs_review", "Necesita revisión"),
                            ("approved", "Aprobada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="nombre original"),
                ),
                ("width", models.PositiveIntegerField(verbose_name="ancho en píxeles")),
                ("height", models.PositiveIntegerField(verbose_name="alto en píxeles")),
                (
                    "file_size",
                    models.PositiveIntegerField(verbose_name="tamaño en bytes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creada"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizada"),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="albums.album",
                        verbose_name="álbum",
                    ),
                ),
            ],
            options={
                "verbose_name": "página",
                "verbose_name_plural": "páginas",
                "ordering": ["page_number"],
                "indexes": [
                    models.Index(
                        fields=["album", "page_number"], name="page_album_order_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("album", "page_number"),
                        name="unique_page_number_per_album",
                    )
                ],
            },
        ),
    ]
